# Generated by Django 3.2.5 on 2021-08-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('language', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=50)),
                ('actress', models.CharField(max_length=50)),
                ('released', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'MovieName',
            },
        ),
    ]
