# Generated by Django 3.2.5 on 2021-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='released',
            field=models.IntegerField(max_length=50),
        ),
    ]
