# Generated by Django 3.2.5 on 2021-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_data_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='data',
            name='released',
            field=models.IntegerField(),
        ),
    ]
