# Generated by Django 3.2.5 on 2021-08-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210811_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
    ]
