# Generated by Django 3.2.5 on 2021-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_data_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='link',
            field=models.URLField(max_length=250),
        ),
    ]
