# Generated by Django 3.2.5 on 2021-08-13 17:32

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_data_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
