# Generated by Django 3.2.5 on 2021-08-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_data_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='thumbnail',
            field=models.CharField(default='', max_length=350),
        ),
    ]
